### ISSUE TITLE
Does the new storage ability help?

### ISSUE THREAD

**Issue by davidhtims** [jrcurtis/subsequencely#12]
Hi, I haven't tried Subsequencely yet as I've been waiting for the 'save' function. Does the new firmware from Novation help; will there be a new version that supports saving soon?

**Comment by jrcurtis** [comment]
Hey david, thanks for creating the issue. I'm going to have a go at this today. I'll definitely be able to make use of this, but the question will just be working out what the most useful things to store will be, and how much space they'll take up.

**Comment by dvhdr** [comment]
@jrcurtis - don't hesitate to drop me a line if you have any questions about the new API!

**Comment by jrcurtis** [comment]
@dvhdr hey, thanks, and thank you for taking the time to add this to the firmware.

I just pushed some changes including a first stab at serializing the app state, but I'm having trouble getting it running on the actual hardware. When I trigger the save function, all the pads flash on and off rapidly for a while and then when I power cycle the hardware, it acts like nothing has been saved. To access the save function in the new version first press the session button, then the setup button, then press the top left pad to save. Turning the launchpad off and on again should load the save.

I haven't really dove into debugging this yet because I wanted to ask you first if there was a problem with my approach, like maybe I shouldn't be making lots of rapid small writes, like I am currently? The code is in [src/serializer.c](https://github.com/jrcurtis/subsequencely/blob/master/src/serializer.c). I added a test implementation of the flash access [here](https://github.com/jrcurtis/subsequencely/blob/master/tools/VirtualLpp/src/VirtualLpp.cpp#L138), maybe I made a mistake with my implementation?

**Comment by jrcurtis** [comment]
Assuming I can get this actually working, here's what I've implemented so far. I can fit all of what I think is the important application state, like midi channels, control codes, sequence settings like clock division, etc. and that takes up 152 bytes. Then there's the actual note data. Each bank (the live note bank and the storage bank that you can copy to) take 768 bytes, so I could only fit the live one into the available space. If a second page of the flash is made available, then that should be more than enough to store the entire application state and all the sequence data as well.

As far as implementation, I went with a dead simple copy of the in memory bytes to the flash storage, with a 4 byte header (a 2 byte app id, and a 2 byte version number) at the beginning, which is checked to match with the current version of the software before attempting to load from the flash. This is very simple, and has no space overhead, but it will not be robust to changes in the memory format, or the addition of new state that needs to be saved. For now, I think the simplicity outweighs the inconvenience of losing your save data whenever a version of the software breaks the data format, but eventually might be worth looking into a more robust serialization scheme.

**Comment by spelljammed** [comment]
Just tried the latest firmware. I primarily use it as a controller for my hardware synths, and much prefer your Subsequencely note input over the stock firmware. 

The storage function does not seem to work for me. I am setting up my midi channels and getting the scales set how I like them, but nothing seems to save when I do Session + Setup + Pad. I see the flashing, but when I power cycle, im back at the base Subsequencely settings. 

Thanks for all this work! Such a good project.

**Comment by jrcurtis** [comment]
Good news, I've been able to get the storage working! I was right to think that it was because I was making many small writes instead of writing a single block of memory all at once. The reason I wanted to write each variable individually is because if I just copied a whole chunk, like a struct for instance, it would involve wasting space on internal data that doesn't need to be saved, and the bigger reason, is that any change to the struct's layout, such as adding a field, reordering the fields, even if they were fields that didn't need to be serialized, would invalidate everybody's saves.

By writing each variable individually, the serialization format only changes when the actual data that needs to be serialized changes, freeing me to make more changes to the code without invalidating everyone's saves as often.

To this end, I decided that since, as I mentioned earlier, there's not enough room at the moment to store the live note bank and the storage note bank, using the save feature entails trashing the storage note bank anyway, so I've used that memory as a buffer to put the non-note data that needs to be saved, then, since the two note banks are contiguous in memory, I can write the entire application state in one call to hal_write_flash().

Sorry for the long post, but I wanted to put my thoughts here in case they were useful to anyone. tl;dr is that the save feature is working for now with the caveat that I have not tested it extensively yet, so there's likely to be bugs, which I'd love to hear about if anyone finds them ;)

**Comment by jrcurtis** [comment]
Oh, btw I plan to make a new video soon detailing this and some other stuff, so it can hopefully be explained more easily there.

**Comment by jrcurtis** [comment]
Here's the video https://www.youtube.com/watch?v=lyAF8q3x_KI&feature=youtu.be&a

**Comment by dvhdr** [comment]
@jrcurtis - argh! I somehow missed this thread - so I'm really glad you've got it working, and apologies for not replying to your earlier comments!

**Comment by jrcurtis** [comment]
@dvhdr No problem. It seems to be working well now. It's a really nice feature to be able to take advantage of.

I'm going to close this now, as the basic functionality is there. Any bugs found with the saving can be put in a new issue.
