### ISSUE TITLE
Notes recorded in live recording mode don't show up in the sequencer

### ISSUE THREAD

**Issue by faroit** [jrcurtis/subsequencely#4]
This is a little confusing since I would have expected that the sequenced notes for each track are shared across the different modes. However, notes recorded in live recording don't show up in the step sequencer and vice versa. Is this intended?

**Comment by jrcurtis** [comment]
They do show up, but it can be a bit difficult to find them. By default the sequencer mode is zoomed out all the way, so any notes that fall in between the beats are not visible, and the Y coordinate is not adjusted based on the contents of the sequence either.

Some things I've thought about to make this more friendly are 1) maybe when zoomed out a pad should be lit up if any of the interstitial steps are non-empty, and/or 2) when switching to the sequencer mode, the X and Y coordinates should automatically be adjusted to show the notes in the sequence if there would otherwise not be any visible.

**Comment by faroit** [comment]
oh yes. I get it..

I would go for 1) ... also see my reply in #3 regarding the zooming ability.
