### ISSUE TITLE
Quantised sequence start

### ISSUE THREAD

**Issue by faroit** [jrcurtis/subsequencely#6]
`Shift+pads: Queue a stopped sequence to start playing on beat.`

To me I would have expect this to be the default case for any step sequencer. I would suggest setting this as defaul. May we can use the shift mode for a quantised launch of two sequences so that the stopped sequence will start when the other sequence resets to the first step. Does that make sense?

**Comment by jrcurtis** [comment]
Yes, makes sense. One of the things I want to avoid is putting too many arbitrary restrictions on what the program can do, since I find that things like playing a sequence out of step with its original position can be the thing that leads to happy creative accidents. Of course, I also want the software to be something that people actually like using, so I'm happy to change the default behaviors and make them more useful.

Both of your suggestions make sense. For your suggested shift behavior, am I right in thinking it would be a workflow of hold shift, then hold a first - already playing - sequence's play button, then press the play button of the stopped sequence?

If this change was made, pressing the pads in session mode could still be used unquantized, which would probably make more sense, as the pads are something that can be "played" so they are more suitable for interactions that need good timing, and the play buttons are more rigid and shouldn't require accurate timing. Anyway, that makes sense to me.

**Comment by faroit** [comment]
:+1: Sounds great to me.
- play button: quantised (synced to beat) :heavy_check_mark: 
- shift+play button: sync to selected track. Maybe this functionality could be simplified so that it can be used without selecting any other patterns at all. I would therefore just sync it to the track which is the first that jumps to step 1. But I also like your idea as well. But I'm not sure if this is easy to learn for beginners
- pads: immediately start playing the sequence

**Comment by jrcurtis** [comment]
I believe that last commit fixes all this up, unless there's anything I missed? I went with shift+play snapping to the first sequence that wraps back around.

**Comment by faroit** [comment]
Works as advertised. Love it
